services:
  line:
    build:
      context: ./googleOAuthDemo
      dockerfile: Dockerfile
    container_name: "google_oauth_demo"
    ports:
      - "9018:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./googleOAuthDemo/bin:/app
